# Markdownlint configuration (YAML)

default: true

# Consistent list indentation
MD007:
  indent: 2

# Relaxed line length limits for readability and prose
MD013:
  line_length: 200
  code_block_line_length: 300
  tables: false
  headings: true

# Disable trailing-punctuation-in-headings (allows ":" etc.)
MD026:
  punctuation: ""

# Disable enforcement of ordered list numbering style
MD029: false

# Allow content before first H1 (e.g., logo block)
MD041: false
