# Markdownlint configuration
# YAML format for consistency across all linting configs

default: true

# Consistent list indentation
MD007:
  indent: 2

# Relaxed line length limits for readability and prose
MD013:
  line_length: 200
  code_block_line_length: 300
  tables: false
  headings: true
  headers: true

# Allow punctuation in headings (e.g., "What's new?")
MD026:
  no-trailing-punctuation: false

# Disable enforcement of ordered list numbering style
MD029: false

# Allow inline HTML for logos, footers, etc.
MD033:
  allowed_elements:
    - hr
    - br
    - a
    - img
    - h1
    - h2
    - h3
    - p
    - em
    - strong

# Allow pre-header content (e.g., logos or HTML blocks)
MD041: false

# Allow mixed emphasis styles (*asterisk* and _underscore_)
MD049:
  emphasis-style: false

# Disable reference link validation (common for shared docs)
MD052:
  reference-links-images: false
