# Base ruleset, then override the noisy bits for GitHub Actions & templates
extends: default

ignore: |
  node_modules/
  dist/
  build/
  vendor/
  **/.venv/
  **/__pycache__/

rules:
  # Turn off line-length complaints
  line-length: disable

  # GitHub Actions & issue/PR templates don't need '---' at top
  document-start: disable

  # Be permissive about indentation but keep it readable
  indentation:
    spaces: 2
    indent-sequences: consistent
    check-multi-line-strings: false

  # Keep colons tidy, but only warn if spacing is odd
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
    level: warning

  # Braces/brackets spacing — warn, don't fail
  braces:
    max-spaces-inside: 1
    level: warning
  brackets:
    max-spaces-inside: 1
    level: warning

  # Reasonable whitespace hygiene
  trailing-spaces:
    level: warning
  new-line-at-end-of-file:
    level: warning
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  # Common false-positives in Actions & templates
  truthy: disable          # avoids nagging about yes/no/on/off literals
  octal-values: disable    # not useful for our use-cases
