name: Documentation update
description: Suggest an update or correction to README, docs, or project policies.
title: "[Docs]: "
labels: ["type: docs", "state: triage"]

body:
  - type: textarea
    id: area
    attributes:
      label: Which document needs updating?
      description: Tell us which file or page this is about (e.g. README, SECURITY.md, CONTRIBUTING.md, org profile).
      placeholder: "Example: .github/README.md"
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current text / problem
      description: Paste the current text or describe what's wrong (typo, broken link, unclear wording, outdated info, etc.)
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Proposed change
      description: If you already know how it should read, add the corrected wording here.
      placeholder: "Proposed new paragraph, fixed link, or updated example"
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add links, screenshots, or references that explain why this change is needed.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/the-lupaxa-project/.github/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
