name: Docs Lint (Markdown + YAML)

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  docs:
    uses: ./.github/.github/workflows/reusable-docs-lint.yml
    permissions:
      contents: read
    with:
      md_globs: "**/*.md"
      yml_globs: |
        **/*.yml
        **/*.yaml